name: Quality Checks
on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    runs-on: [alpine]
    steps:
      - name: Clone repository
        run: |
          git clone --quiet ${{ gitea.server_url }}/${{ gitea.repository }}.git .
          git checkout ${{ gitea.sha }}

      - name: Install dependencies
        run: |
          apk update --quiet
          apk add --quiet --no-cache \
            make \
            python3 \
            py3-pip \
            py3-virtualenv \
            py3-gobject3 \
            py3-cairo \
            gtk4.0-dev \
            libadwaita-dev \
            gtksourceview5-dev \
            webkit2gtk-6.0-dev \
            xvfb-run

      - name: Build
        run: make build

      - name: Test
        run: xvfb-run make test
